from enum import IntEnum, auto

class Rule(IntEnum):
	NONE = -1
	PROGRAM = auto()
	DEFINE = auto()
	MORE_DEFINES = auto()
	STMT_LIST = auto()
	STMT = auto()
	LITERAL = auto()
	QUOTED_LIT = auto()
	MORE_TOKENS = auto()
	PARAM_LIST = auto()
	ELSE_PART = auto()
	STMT_PAIR = auto()
	STMT_PAIR_BODY = auto()
	ACTION = auto()
	ANY_OTHER_TOKEN = auto()

class Token(IntEnum):
	NONE = -1
	LAMBDA = auto()
	IDENT_T = auto()
	NUMLIT_T = auto()
	STRLIT_T = auto()
	CONS_T = auto()
	IF_T = auto()
	COND_T = auto()
	DISPLAY_T = auto()
	NEWLINE_T = auto()
	LISTOP_T = auto()
	AND_T = auto()
	OR_T = auto()
	NOT_T = auto()
	DEFINE_T = auto()
	NUMBERP_T = auto()
	SYMBOLP_T = auto()
	LISTP_T = auto()
	ZEROP_T = auto()
	NULLP_T = auto()
	STRINGP_T = auto()
	MODULO_T = auto()
	ELSE_T = auto()
	PLUS_T = auto()
	MINUS_T = auto()
	DIV_T = auto()
	MULT_T = auto()
	EQUALTO_T = auto()
	GT_T = auto()
	LT_T = auto()
	GTE_T = auto()
	LTE_T = auto()
	LPAREN_T = auto()
	RPAREN_T = auto()
	QUOTE_T = auto()
	ERROR_T = auto()
	EOF_T = auto()
	MAX_TOKENS = auto()